version: '3.3'
services:
  odoo:
    build:
      context: https://github.com/EmilMoe/odoo10.git
    env_file:
      - odoo.conf
    volumes:
      - ./odoo.conf:/etc/odoo/odoo.conf
      - ./addons:/mnt/addons
      - ./data:/var/lib/odoo
      - ./odoo:/usr/lib/python2.7/dist-packages/odoo
    ports:
      - "8069:8069"
      
  db:
    image: postgres:9.6
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"

