version: '3.3'
services:
  odoo:
    build:
      context: https://github.com/EmilMoe/odoo10.git
    volumes:
      - ./odoo.conf:/etc/odoo/odoo.conf
      - ./addons:/mnt/addons
      - ./data:/var/lib/odoo
      - modules:/usr/lib/python2.7/dist-packages/odoo/addons
    ports:
      - "8069:8069"
  db:
    image: postgres:9.6
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
volumes:
  postgres:
  modules:
